### ISSUE TITLE
Temperature_and_more looses connection after running uninterupted for two days

### ISSUE THREAD

**Issue by pietervandereems** [createcandle/Devices#2]
Build the temperature sensor (https://www.candlesmarthome.com/temperature).
After running for two days (powered by it's own usb powersupply) the gateway shows the "thing" as being disconnected. The sensor seems to function correctly (showing the current temperature and the screen reacts (turning on/off) to a "click"). It does not show any errors on the screen.

**Comment by createcandle** [comment]
I've run tests on the latest code, and it seems to run stable here. Could you test the latest code? If you are using the Candle Manager it will download new new code automatically.

**Comment by createcandle** [comment]
I've created another test device, this time without a touch screen, and that is also purring along just fine. So I'm going to close this issue. If you are still experiencing issues, don't hesitate to re-open.
