### ISSUE TITLE
Compiling of Candle_receiver fails if "Show transmission details" is not enabled

### ISSUE THREAD

**Issue by WetenSchaap** [createcandle/Devices#3]
Uploading Candle_receiver to the Arduino currently fails when "Show transmission details" is not enabled. 

`Error: /home/node/.mozilla-iot/addons/Candle-manager-addon/code/Candle_receiver/Candle_receiver.ino: In function 'void setup()':`

I think it may be caused by  the following lines in setup()

`  
send(transmission_quality_message.setSensor(CHILD_ID_TX_OK).set(txOK)); // Send the good transmissions value
  send(transmission_quality_message.setSensor(CHILD_ID_TX_ERR).set(txERR)); // Send the failed transmissions value
`

Since `transmission_quality_message` is not defined if `SHOW_TRANSMISSION_DETAILS` is not defined.

**Comment by createcandle** [comment]
Yes, you were right. This has been fixed.
