### ISSUE TITLE
Candle smarthome device weather sensor error

### ISSUE THREAD

**Issue by Eshu100** [createcandle/Devices#5]
Ik heb een weer sensor gemaakt en bij de check stap in de Candle Manager krijg ik de error !NOT CONNECTED TO GATEWAY
Als ik dan naar de WebThings ga en op de plus klik komt de device niet tevoorschijn. Hij kan het apparaat niet vinden.

Ik heb al een aantal keer het opnieuw geprobeerd. Stekker eruit, candle manager opgestart, stekker weer aangesloten en dan ziet ie het apparaat wel. Dus klik op temperatuur en dan loopt ie de stappen ook wel door.
Tot het laatste stukje.

Wat kan ik doen om deze error op te lossen?

**Comment by createcandle** [comment]
De weer sensor lukt het schijnbaar niet om verbinding te maken met de Candle Controller.
- Heb je wel eerst een Candle Receiver gemaakt en ingeplugd? Je weer sensor probeert daar verbinding mee te leggen.
- Heb je de MySensors addon wel geinstalleerd?
- Als je wel een Candle Receiver ingeplugd hebt: heb je tussendoor toevallig handmatig het encryptie paswoord aangepast? Alle apparaten, inclusief de Candle Receiver, moet hetzelfde paswoord gebruiken om met elkaar te kunnen spreken.

**Comment by Eshu100** [comment]
Hallo,

Dank voor het antwoord.
Maar het is inmiddels opgelost. Het werkt. Heb ook al een tweede gemaakt.

Alleen moet een sterkere receiver maken. De weerstation op de slaapkamer heeft niet altijd verbinding. De receiver staat namelijk beneden.

Hartelijke groet,
Esther Poll

14 nov. 2020 12:00:47 Candle - the privacy friendly smart home <notifications@github.com>:

> De weer sensor lukt het schijnbaar niet om verbinding te maken met de Candle Controller.
> 
* > Heb je wel eerst een Candle Receiver gemaakt en ingeplugd? Je weer sensor probeert daar verbinding mee te leggen.
* > Heb je de MySensors addon wel geinstalleerd?
* > Als je wel een Candle Receiver ingeplugd hebt: heb je tussendoor toevallig handmatig het encryptie paswoord aangepast? Alle apparaten, inclusief de Candle Receiver, moet hetzelfde paswoord gebruiken om met elkaar te kunnen spreken.

**Comment by createcandle** [comment]
Fijn dat 't opgelost is. De apparaten kunnen ook signalen doorgeven om zo grotere afstanden te overbruggen. Maar een sterkere ontvanger is zeker fijn. Op het blog kun je lezen hoe je die maakt.
